### ISSUE TITLE
Python 3.7.0

### ISSUE THREAD

**Issue by iCrazyBlaze** [altendky/pyqt5-tools#13]
I recently tried to install pyqt-tools on Windows with Python 3.7.0, and it said that no versions could be found.

```
  Could not find a version that satisfies the requirement pyqt5-tools (from versions: )
No matching distribution found for pyqt5-tools
```

**Comment by altendky** [comment]
Sure thing...  if only it just worked.  For some reason the environment variables from the build aren't showing up in 3.7.  *sigh*  I'll keep coming back to this stuff a couple times a week maybe to try to work it out.  I really don't understand why I have such a hard time with this.

**Comment by aagontuk** [comment]
Is there any work around for this?

**Comment by altendky** [comment]
@aagontuk, sorry, I got the env var issue fixed but didn't come back and update the ticket.  It was something about how I was subprocessing to get the `vcvarsall.bat` env modifications.

**Comment by BravoAlpha59** [comment]
pip install of pyqt5-tools is still failing with "version not found" for 5.11 and 3.7. Is there a different method to use. It seemed like you had indicated it was patched up and ready for use.

**Comment by altendky** [comment]
I haven't gotten 5.11 building yet, sorry.

**Comment by jnickscott** [comment]
Hi I'm very noob and thanks for putting time into this. I found this because I'm trying to learn Python / PyQt and installed it but I can't find the designer.exe to launch PyQt framework. I understand this project is to make that easier, is there no other way to launch PyQt designer? just seems very strange to me...

**Comment by aquilesC** [comment]
@jnickscott you can install the official Qt package which will have QtDesigner bundled. However, it is a several GB installation. If you are on Linux, installing the designer is only one command away.

**Comment by liyangzbx** [comment]
I used the command 'pip install PyQt5-tools' on python3.7, it said 'Could not find a version'. However, I downloaded 'PyQt5_Tools-5.7.dev1-py3-none-any.whl' and installed it offline on 32-bit python3.7 successfully.And I used the same method to install on 64-bit python3.7,but it didn't work.

**Comment by altendky** [comment]
@liyangzbx, thanks for the feedback.  Can you explain what you did and what didn't work in a bit more detail?  Though, I'm not even building 5.7 anymore as  it and 5.11 are in different AppVeyor images.  I may later figure out how to deal with that but for now it's going to be 5.9+.  (if i ever get it building, my apologies for being terrible at this)

**Comment by altendky** [comment]
https://ci.appveyor.com/project/KyleAltendorf/pyqt5-tools/build/555

If you want to try them out...  (build in progress)

**Comment by altendky** [comment]
v1.3 released: https://www.riverbankcomputing.com/pipermail/pyqt/2018-September/040940.html

**Comment by t1m0thyj** [comment]
@ipsod It should be fixed now I believe, I was able to install it in Python 3.7 after v1.3 was released with `pip install -U pyqt5-tools`. Make sure you have the latest version of `pip` installed if you are having problems.

**Comment by altendky** [comment]
There are definitely various 3.7 builds.  All the builds seem to work for some and not for others, at least for the designer plugin.  If you have an problem, do open a new issue and report however much info you can.

**Comment by Catorod** [comment]
I'm still having this problem with pip 18.1 in Fedora 29, Python 3.7.2

**Comment by altendky** [comment]
@Catorod, there are definitely 3.7 files uploaded.

https://pypi.org/project/pyqt5-tools/#files

Please do open a new issue and provide the complete command and output.  Whatever `pip` you run, also run it with `--version` and share that command and output.

**Comment by altendky** [comment]
@Catorod actually...  :[ should have jumped out at me immediately...  there isn't `pyqt5-tools` for Linux yet.  See #21.

**Comment by vickylance** [comment]
I am still getting this error when I install with `pipenv install pyqt5-tools` on macos

**Comment by altendky** [comment]
@vickylance this is still a Windows only project.  Sorry.  I would like to support other platforms but...  lots of things to do, as always.

**Comment by vickylance** [comment]
@altendky No issues will use Windows 👍

**Comment by 7h0m4sS4** [comment]
same issue by using Python 3.8 on windows 10 using  pip version 19.2.3.
I downgraded to Python 3.7.5 and it works again.

**Comment by altendky** [comment]
@7h0m4sS4 see #35

**Comment by wxjttxs** [comment]
ubuntu16 python3.7 pip 20.0.2 same error  .     
ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none)

**Comment by altendky** [comment]
@wxjttxs see #21

**Comment by harshilishere** [comment]
any update for ubuntu?! giving the same error when tried to install with pip.

**Comment by altendky** [comment]
@harshilishere, Linux has not yet been supported...  but see #21.  There's a wheel linked in https://github.com/altendky/pyqt5-tools/issues/21#issuecomment-586671405 that I've had work and more at https://github.com/altendky/pyqt5-tools/actions if you dare try them.

**Comment by Admund20** [comment]
I have the same issue with pyqt5-tools. I cannot install it in windows 10. Error: Could not find a version that satisfies the requirement. I run Python 3.9 and pip 20.2.4. Any help would be much appreciated.

**Comment by altendky** [comment]
@Admund20 see #59.  Also #58 and #62 for context on the present situation.

**Comment by Admund20** [comment]
so what should I do? I really need to install pyqt5-tools.
